# Generated by Django 5.1.5 on 2025-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedWorkouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=150)),
                ('workout_instruction', models.CharField(max_length=300)),
                ('workout_description', models.CharField(max_length=500)),
                ('muscle_group', models.CharField(max_length=50)),
            ],
        ),
    ]
