# Generated by Django 5.1.5 on 2025-01-31 23:35

from django.db import migrations
from workouts_main.workout_data import DEFINED_WORKOUTS

def load_workouts(apps, schema_editor):
    workouts = apps.get_model('workouts_main', 'DefinedWorkouts')
    for workout in DEFINED_WORKOUTS:
        store_corporate = workouts(workout_name = workout['workout_name'], workout_instruction =workout['workout_instruction'], 
                                workout_description =workout['workout_description'], muscle_group = workout['muscle_group'])
        store_corporate.save()
    
def delete_workouts(apps, schema_editor):
    workouts = apps.get_model('workouts_main', 'DefinedWorkouts')
    workouts.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_workouts, delete_workouts)
    ]




