# Generated by Django 5.1.5 on 2025-02-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts_main', '0002_auto_20250131_2335'),
        ('workouts_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplans',
            name='excercise',
        ),
        migrations.RemoveField(
            model_name='workoutplans',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='workoutplans',
            name='daily_session',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='WorkoutInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(null=True)),
                ('repetitions', models.IntegerField(null=True)),
                ('sets', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_main.definedworkouts')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts_planner.workoutplans')),
            ],
        ),
    ]
