# Generated by Django 5.1.5 on 2025-02-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('workouts_main', '0002_auto_20250131_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackworkouts',
            name='excercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workouts_main.definedworkouts'),
            preserve_default=False,
        ),
    ]
